# LEMP PLAYBOOK
---
- hosts: "all"
  become: yes
  tasks:
  - set_fact:
      nodeversion: "1.5.0"
  - name: "Unarchive node_exporter"
    ansible.builtin.unarchive:
      src: "https://github.com/prometheus/node_exporter/releases/download/v{{nodeversion}}/node_exporter-{{nodeversion}}.linux-amd64.tar.gz"
      dest: /tmp
      remote_src: yes
  - name: "Create user"
    ansible.builtin.user:
      name: node_exporter
      shell: /bin/false
  - name: "Copy node_exporter"
    ansible.builtin.copy:
      src: /tmp/node_exporter-{{nodeversion}}.linux-amd64/node_exporter
      dest: /usr/local/bin
      remote_src: yes 
      owner: node_exporter
      group: node_exporter
      mode: u=rwx,g=rx,o=rx
  - name: "Copy node_exporter.service"
    ansible.builtin.copy:
      src: /etc/ansible/download/node_exporter.service
      dest: /etc/systemd/system
      remote_src: no  
  - name: "Restart daemon service"
    ansible.builtin.systemd:
      daemon_reload: yes
  - name: "Start node_exporter.service"
    ansible.builtin.systemd:
      name: node_exporter.service
      state: started
      enabled: yes
